services:
  weatherstation:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: /docker/env_dev/weatherstation.env
    environment:
      NODE_ENV: development
    volumes:
      - './dist:/usr/src/app/dist'
    ports:
      - 3000:3000
      - 9229:9229
    command: ["npm", "run", "start.dev"]