version: '3.4'

services:
  weatherstationelsnerp03:
    image: weatherstationelsnerp03
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
