services:
  weatherstation:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: /docker/env_dist/weatherstation.env
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000